environment:
  matrix:
    - nodejs_version: '20'
    - nodejs_version: '22'

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm run wintest
